version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-shop
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./environment/mysql-entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 33063:3306

  webserver:
    container_name: webserver
    build:
      context: ./
    environment:
      XDEBUG_CONFIG: remote_host=darkArmy
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - .:/var/www/html
    ports:
      - 8800:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
