-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 17:08:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop_db` ;

-- -----------------------------------------------------
-- Schema shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `shop_db` ;

-- -----------------------------------------------------
-- Table `client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname_first` VARCHAR(45) NOT NULL,
  `surname_last` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `ci` VARCHAR(9) NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ci_UNIQUE` (`ci` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(150) NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `confirmed` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_has_product_client_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_product_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_items` (
  `order_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `item_id`),
  INDEX `fk_order_has_item_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_order_has_item_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `client`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop_db`;
INSERT INTO `client` (`id`, `name`, `surname_first`, `surname_last`, `email`, `password`, `ci`, `address`) VALUES (DEFAULT, 'Pepe', 'Fernandez', 'Lopez', 'pepe@gmail.com', 'pepe', '123456789', 'calle faisan 2, bajo 3, Madrid');
INSERT INTO `client` (`id`, `name`, `surname_first`, `surname_last`, `email`, `password`, `ci`, `address`) VALUES (DEFAULT, 'Javier', 'Lopez', 'Diaz', 'jlopez@gmail.com', 'jlopez', '987654321', 'av juan carlos I numero 46');

COMMIT;


-- -----------------------------------------------------
-- Data for table `item`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop_db`;
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Algodon', 'sin tratamientos quimicos', 00179);
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Resistencia 0,5 Ohm', 'para buenas nubarradas', 00359);
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Liquido Fresa', 'dulce', 02000);
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Aroma Frutos del Bosque', 'concentrado', 00500);
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Base 80/20', 'para hacerte tus liquidos', 00750);
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Lemon Sherbets Sweets 50ml - Dinner Lady', 'El eliquid Lemon Sherbets Sweetd de Dinner Lady', 01695);
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Topside Dual Mod 200w - Dovpo', 'fantastico mod', 08250);
INSERT INTO `item` (`id`, `name`, `description`, `price`) VALUES (DEFAULT, 'Aroma Green with Envy 30ml - Chefs Flavours', 'Riquisimo', 01110);

COMMIT;

